config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # ROUTES:
  # HTTP VERBS: get, post, put, patch, delete
  # verb 'url/path' => 'controller#action'

  # SHOW Routes:
  get 'students'      => 'students#index'
  get 'students/:id'  => 'students#show', as: 'student', id: /\d+/ #<= constraints: http://guides.rubyonrails.org/routing.html#segment-constraints
  # same as:
  # resources 'students', only: [:index, :show]

  root 'students#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence:true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
# Controller - with its actions, which may call private methods - represents
#   visitors' / users' interface to Model's CRUD methods aka resources

class StudentsController < ApplicationController
  def index
    @students = Student.order( :name ) # Load all students ordered by name
    # @students = Student.all
  end
  # Automatically load the app/views/students/index.html.erb

  def show
    @student = find_student # Load the student mentioned by id in the route
  end
  # Automatically load the app/views/students/show.html.erb

  private

    def find_student
      Student.find params[:id]
    end

    def student_params
      params.require( :student ).permit( :name )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WithoutMagic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :p, msg, class:"#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <h1>Student Records Application</h1>
  <!--
    <nav>
      <ul>
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </nav>
   -->
</header>

app/views/students/_student.html.erb
<!--

• The partial name matches the model name (with a prepended underscore).
• The variable name used in the partial matches the partial name.

-->

<div class="student">
  <p>
    <strong>Name:</strong> <%= link_to student.name, student %> <!-- a bit of magic there -->
    <!-- <strong>Name:</strong> <%#= link_to student.name, student_path( student ) %> -->
    <!-- <%#= link_to 'Edit', [:edit, student] %> -->
    <!-- <%#= link_to 'Edit', edit_student_path( student ) %> -->
    <!-- <%#= link_to 'Delete', student, method: :delete, data:{ confirm:'Heads up! Delete the student?' } %> -->
  </p>
</div>

app/views/students/index.html.erb
<h2>All Students</h2>

<%= render @students %>
<!--
• Most rails magic here:
:: render method infers collection was passed
:: ( perhaps with: @students.is_a?( Array ) )
:: => it runs partial for each member
• The partial name matches the model name (with a prepended underscore).
• The variable name used in the partial matches the partial name.
-->

<!-- less magic: render runs iteration -->
<%#= render partial: 'student', collection: @students %>

<%
=begin %>
  <% @students.each do |student| %>
    <%#= render student %>              <%# a bit of magic: shorter %>
    <%#= render partial: 'student', object: student %>
  <% end %>
<%
=end %>

app/views/students/show.html.erb
<h2>Student Information</h2>

<%= render @student %>
<!--
• Here with some rails magic:
:: render method infers name of the partial and the variable used inside
• for this to work:
:: The partial name matches the model name (with a prepended underscore).
:: The variable name used in the partial matches the partial name.
-->

<!-- explicit, self-explanatory form of rendering a partial -->
<%#= render partial: 'student', object: @student %>

<p>
  <%= link_to 'Back to All Students', students_path %>
</p>